name: My First Workflow

# Когда запускать план? При каждом пуше в репозиторий
on: [push]

# Какие цеха (задачи) у нас есть?
jobs:
  say-hello-job: # Название нашего цеха
    runs-on: ubuntu-latest # Выдайте нам сервер с последней Ubuntu!
    
    # Что конкретно будут делать рабочие в цеху?
    steps:
      - name: Print a greeting # Название шага
        run: echo "Hello World! I am running on GitHub Actions!" # Команда Linux
