name: My First Workflow

# Когда запускать план? При каждом пуше в репозиторий
on: [push]

# Какие цеха (задачи) у нас есть?
jobs:
  say-hello-job: # Название нашего цеха
    runs-on: ubuntu-latest # Выдайте нам сервер с последней Ubuntu!
    
    # Что конкретно будут делать рабочие в цеху?
    steps:
      # Шаг 1: Используем готовый экшен для скачивания кода
      - name: Checkout repository
        uses: actions/checkout@v4

      # Шаг 2: Проверяем, на месте ли код
      - name: List files
        run: ls -la

      # Шаг 3: Проверяем версию Docker Compose
      - name: Check Docker Compose version
        run: docker compose version
      
      # Шаг 4: Собираем наши образы
      - name: Build Docker images
        run: docker compose build


